name: Release

on: 
  workflow_dispatch:
  push:
    tags:
      - '*'

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

permissions:
  contents: write

jobs:
  buildAndRelease:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    # compile for old libc to cover more linux versions
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Install Samba client dev headers
      run: |
        sudo apt-get update
        sudo apt-get install -y libsmbclient-dev

    # Update references
    - name: Git Sumbodule Update
      run: |
        git submodule update --init
    
    - name: Get Conan
      # You may pin to the exact commit or the version.
      # uses: turtlebrowser/get-conan@c171f295f3f507360ee018736a6608731aa2109d
      uses: turtlebrowser/get-conan@v1.2

    - name: Create default profile
      run: conan profile detect
      
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_PROJECT_TOP_LEVEL_INCLUDES=${{github.workspace}}/conan_provider.cmake

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j 18

    - name: Prep release
      shell: bash
      run: |
        rm ./Release/Beacons/.gitignore
        mv ./Release/Beacons ./Release/LinuxBeacons
        rm ./Release/Modules/.gitignore
        mv ./Release/Modules ./Release/LinuxModules
        tar -zcvf Release.tar.gz Release

    - name: Upload release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: Release.tar.gz
        asset_name: Release.tar.gz
        tag: ${{ github.ref }}
        overwrite: true
        body: "Linux beacons and modules"

